# Pandas Exercises

## Shift + Tab for documentation

## Creating DataFrames and Using Sample Data Sets

This is the Jupyter Notebook runnable exercises version of the article

In [30]:
import pandas as pd
import numpy as np
import seaborn as sb

**1.** Using NumPy, create a Pandas DataFrame with five rows and three columms:

In [31]:
a = np.array([[1,5,8],[11,5,4],[44,57,5],[11,5,4],[44,57,5]])
df = pd.DataFrame(a)
df

    0   1  2
0   1   5  8
1  11   5  4
2  44  57  5
3  11   5  4
4  44  57  5

**2.** For a Pandas DataFrame created from a NumPy array, what is the default behavior for the labels for the columns?  For the rows?

In [32]:
# Rows = 0 to end
# columsn = 0 to end
df

    0   1  2
0   1   5  8
1  11   5  4
2  44  57  5
3  11   5  4
4  44  57  5

**3.** Create a second DataFrame as above with five rows and three columns, setting the row labels to the names of any five major US cities and the column labels to the first three months of the year.

In [33]:
df = pd.DataFrame(a, index = ["Texas", "California", "Greenland", "NewYork", "Venezuala"], columns = ["Jan","Feb","March"])
df

            Jan  Feb  March
Texas         1    5      8
California   11    5      4
Greenland    44   57      5
NewYork      11    5      4
Venezuala    44   57      5

**4.** You recall that the Seaborn package has some data sets built in, but can't remember how to list and load them. Assuming the functions to do so have "data" in the name, how might you locate them?  You can assume a Jupyter Notebook / IPython environment and explain the process, or write the code to do it in Python.

In [34]:
import seaborn as sns
df = sns.load_dataset("tips")
df.sample(10)

     total_bill    tip     sex smoker   day    time  size
199       13.51   2.00    Male    Yes  Thur   Lunch     2
118       12.43   1.80  Female     No  Thur   Lunch     2
185       20.69   5.00    Male     No   Sun  Dinner     5
192       28.44   2.56    Male    Yes  Thur   Lunch     2
230       24.01   2.00    Male    Yes   Sat  Dinner     4
125       29.80   4.20  Female     No  Thur   Lunch     6
33        20.69   2.45  Female     No   Sat  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3
196       10.34   2.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4

## Loading data from CSV

**5**. Zillow home data is available at this URL: https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv

Open this file as a DataFrame named df_homes in Pandas.

In [35]:
df_homes = pd.read_csv("https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv")
df_homes.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2025-02-28,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30
0,102001,0,United States,country,NaN,121365.463017,121578.983773,121843.780950,122411.718918,123065.347427,...,360639.085047,360365.882152,359841.918311,359161.728607,358549.348441,358126.082695,357900.244881,358139.907469,358570.726255,359241.248814
1,394913,1,"New York, NY",msa,NY,217048.914950,217971.250375,218902.128288,220788.447146,222741.795647,...,683063.089259,684751.535661,687173.496480,688933.036680,690400.936533,691567.341599,692353.209509,693746.473781,696069.806090,699394.634661
2,753899,2,"Los Angeles, CA",msa,CA,218336.580065,219149.069165,220231.296899,222384.566542,224739.568479,...,948074.673902,943052.689223,938798.754881,934095.397500,929804.957480,927250.711189,926195.042763,927236.358557,929617.284624,932886.242451
3,394463,3,"Chicago, IL",msa,IL,151721.660042,151862.110101,152129.599712,152795.047391,153595.500906,...,326483.919256,327320.371223,327914.592965,328201.936285,328558.836926,329388.734181,330373.317156,331691.388829,332981.532008,334511.786740
4,394514,4,"Dallas, TX",msa,TX,126887.587653,126944.103828,127009.074957,127177.798153,127400.255068,...,372494.812737,371001.024231,368886.369472,366484.365155,364134.164489,362129.302053,360775.171809,360131.881806,359785.324832,359523.202747

**6.** Save the DataFrame, df_homes, to a local CSV file, "zillow_home_data.csv".

In [54]:
df_homes.to_csv("zillow_home_data.csv")

**7.** Load zillow_home_data.csv back into a new Dataframe, df_homes_2

In [55]:
df_homes_2 = pd.read_csv("zillow_home_data.csv")
df_homes_2.tail(7)

,Unnamed: 0,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,...,2025-02-28,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30
888,888,395142,933,"Sweetwater, TX",msa,TX,NaN,NaN,NaN,NaN,...,109240.671948,108580.811675,107327.600793,106388.366240,105412.424762,104778.864348,104381.347702,104311.501781,104810.657333,105536.256269
889,889,394968,934,"Pecos, TX",msa,TX,NaN,NaN,NaN,NaN,...,171137.056537,172430.454866,171113.752988,169167.794871,167175.230265,166369.486728,166171.838005,165088.311640,165263.693059,165859.083876
890,890,753929,935,"Zapata, TX",msa,TX,NaN,NaN,NaN,NaN,...,133514.675279,132781.438720,130685.614769,128397.504390,126235.703054,125502.898394,125045.903273,124278.819341,123296.785163,122508.051532
891,891,394743,936,"Ketchikan, AK",msa,AK,NaN,NaN,NaN,NaN,...,355352.000440,356097.700891,357694.059413,360593.048986,364569.188569,368550.555762,372669.696099,376094.651971,379367.392421,381733.048938
892,892,753874,937,"Craig, CO",msa,CO,98629.019558,98881.220858,99350.753613,100019.411625,...,293364.104906,293681.083315,294953.804884,296344.618371,297402.870382,298553.280741,299565.168301,300821.226874,301111.592432,300667.792859
893,893,395188,938,"Vernon, TX",msa,TX,NaN,NaN,NaN,NaN,...,98254.714921,97086.075963,95629.430696,94456.342850,93598.594960,93001.199664,92743.248874,92388.650920,92194.298514,92668.330706
894,894,394767,939,"Lamesa, TX",msa,TX,NaN,NaN,NaN,NaN,...,101293.102592,101721.889379,102032.929261,101903.341545,101772.868257,101766.259832,101529.391196,101475.618876,101775.163123,103043.918352

**8.** Compare the dimensions of the two DataFrames, df_homes and df_homes_2.  Are they equal?  If not, how can you fix it?

df = df.drop('column_name', axis=1)
df = df.drop(columns=['column_name'])
df = df.drop(['column_name_1', 'column_name_2'], axis=1)
df.drop(['non_existent_col', 'column_name_2'], axis=1, inplace=True, errors='ignore')
df = df.drop(df.columns[[0, 2]], axis=1)
del df['column_name']

In [56]:
print(df_homes.columns)
print(df_homes_2.columns)

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31',
       ...
       '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30',
       '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30'],
      dtype='object', length=316)
Index(['Unnamed: 0', 'RegionID', 'SizeRank', 'RegionName', 'RegionType',
       'StateName', '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30',
       ...
       '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30',
       '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30'],
      dtype='object', length=317)

In [57]:
print(df_homes.shape)
print(df_homes_2.shape)

(895, 316)
(895, 317)

In [58]:
df_homes_2.drop(df_homes_2.columns[[0,0]], axis=1, inplace = True)
df_homes_2.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31',
       ...
       '2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31', '2025-06-30',
       '2025-07-31', '2025-08-31', '2025-09-30', '2025-10-31', '2025-11-30'],
      dtype='object', length=316)

In [59]:
print(df_homes.shape)
print(df_homes_2.shape)

(895, 316)
(895, 316)

**9.** A remote spreadsheet showing how a snapshot of how traffic increased for a hypothetical website is available here: https://github.com/CodeSolid/CodeSolid.github.io/raw/main/booksource/data/AnalyticsSnapshot.xlsx. Load the worksheet page of the spreasheet data labelled "February 2022" as a DataFrame named "feb".  Note: the leftmost column in the spreadsheet is the index column.

In [66]:
feb = pd.read_excel("https://github.com/CodeSolid/CodeSolid.github.io/raw/main/booksource/data/AnalyticsSnapshot.xlsx", sheet_name = "February 2022")
feb

   Unnamed: 0  This Month  Last Month  Month to Month Increase
0       Users        1800         280                 5.428571
1   New Users        1700         298                 4.704698
2  Page Views        2534         436                 4.811927

**10.** The "Month to Month Increase" column is a bit hard to understand, so ignore it for now.  Given the values for "This Month" and "Last Month", create a new column, "Percentage Increase".

In [69]:
feb["Percentage Increase"] = ((feb["This Month"] - feb["Last Month"])/feb["Last Month"]) * 100
feb

,Unnamed: 0,This Month,Last Month,Month to Month Increase,Percentage Increase
0,Users,1800,280,5.428571,542.857143
1,New Users,1700,298,4.704698,470.469799
2,Page Views,2534,436,4.811927,481.192661

## Basic Operations on Data

**11.** Using Seaborn, get a dataset about penguins into a dataframe named "df_penguins".  Note that because all of the following questions depend on this example, we'll provide the solution here so no one gets stuck:

In [67]:
df_penguins = sb.load_dataset('penguins')

**12.** Write the code to show the the number of rows and columns in df_penguins

In [70]:
df_penguins.shape

(344, 7)

**13.** How might you show the first few rows of df_penguins?

In [71]:
df_penguins.head(7)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female

**14.** How can you return the unique species of penguins from df_penguins?  How many unique species are there?

In [72]:
df_penguins["species"].value_counts()

Adelie       152
Gentoo       124
Chinstrap     68
Name: species, dtype: int64

In [75]:
print(df_penguins["species"].unique())
print(df_penguins["species"].nunique())

['Adelie' 'Chinstrap' 'Gentoo']
3

**15.** What function can we use to drop the rows that have missing data?

In [77]:
df_penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [78]:
df_penguins.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [80]:
df_penguins.dropna(axis=0, inplace=True)
df_penguins.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

**16.** By default, will this modify df_penguins or will it return a copy?

#By default it will return a copy, but by using arg (inplace = True) we can make permanent changes

**17.** How can we override the default?

In [81]:
df_penguins.dropna(axis=0, inplace=True)
df_penguins.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

**18.** Create a new DataFrame, df_penguins_full, with the missing data deleted.

In [83]:
df_penguins_full = df_penguins.copy()
print(df_penguins_full.isnull().sum())
df_penguins_full.head()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male

**19.** What is the average bill length of a penguin, in millimeters, in this (df_full) data set?

In [84]:
df_penguins_full["bill_length_mm"].mean()

43.99279279279279

**20.** Which of the following is most strongly correlated with bill length?  a) Body mass?  b) Flipper length?  c) Bill depth?  Show how you arrived at the answer.

In [90]:
df_penguins_full.corr()

C:\Users\IIITDMK\AppData\Local\Temp\ipykernel_25072\4262677287.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_penguins_full.corr()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
bill_length_mm,1.000000,-0.228626,0.653096,0.589451
bill_depth_mm,-0.228626,1.000000,-0.577792,-0.472016
flipper_length_mm,0.653096,-0.577792,1.000000,0.872979
body_mass_g,0.589451,-0.472016,0.872979,1.000000

In [97]:
df_penguins_full.corr().loc["bill_length_mm"].sort_values(ascending = False).head(2)

C:\Users\IIITDMK\AppData\Local\Temp\ipykernel_25072\158614948.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_penguins_full.corr().loc["bill_length_mm"].sort_values(ascending = False).head(2)

bill_length_mm       1.000000
flipper_length_mm    0.653096
Name: bill_length_mm, dtype: float64

**21.** How could you show the median flipper length, grouped by species?

In [107]:
grouped = df_penguins_full.groupby("species")["flipper_length_mm"].median()
grouped

species
Adelie       190.0
Chinstrap    196.0
Gentoo       216.0
Name: flipper_length_mm, dtype: float64

In [108]:
grouped = df_penguins_full.groupby("species")["flipper_length_mm"].median().idxmax()
grouped

'Gentoo'

In [100]:
grouped.sort_values(ascending = False).head(1)

species
Gentoo    216.0
Name: flipper_length_mm, dtype: float64

**22.** Which species has the longest flippers?

In [111]:
long = df_penguins_full["flipper_length_mm"].idxmax()
print(long)
df_penguins_full.iloc[long]

283

species              Gentoo
island               Biscoe
bill_length_mm         46.4
bill_depth_mm          15.6
flipper_length_mm     221.0
body_mass_g          5000.0
sex                    Male
Name: 291, dtype: object

In [112]:
df_penguins_full.iloc[long]["flipper_length_mm"]

221.0

**23.** Which two species have the most similar mean weight?  Show how you arrived at the answer.

In [113]:
similiar = df_penguins_full.groupby("species")["body_mass_g"].mean()
similiar

species
Adelie       3706.164384
Chinstrap    3733.088235
Gentoo       5092.436975
Name: body_mass_g, dtype: float64

**24.** How could you sort the rows by bill length?

In [115]:
sort = df_penguins_full.sort_values(by = "bill_length_mm")
sort.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
142,Adelie,Dream,32.1,15.5,188.0,3050.0,Female
98,Adelie,Dream,33.1,16.1,178.0,2900.0,Female
70,Adelie,Torgersen,33.5,19.0,190.0,3600.0,Female
92,Adelie,Dream,34.0,17.1,185.0,3400.0,Female
18,Adelie,Torgersen,34.4,18.4,184.0,3325.0,Female
54,Adelie,Biscoe,34.5,18.1,187.0,2900.0,Female
80,Adelie,Torgersen,34.6,17.2,189.0,3200.0,Female
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male
100,Adelie,Biscoe,35.0,17.9,192.0,3725.0,Female
52,Adelie,Biscoe,35.0,17.9,190.0,3450.0,Female

**25.** How could you run the same sort in descending order?

In [118]:
sort1 = df_penguins_full.sort_values(by = "bill_length_mm", ascending = False)
sort1.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
253,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,Male
169,Chinstrap,Dream,58.0,17.8,181.0,3700.0,Female
321,Gentoo,Biscoe,55.9,17.0,228.0,5600.0,Male
215,Chinstrap,Dream,55.8,19.8,207.0,4000.0,Male
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,Male
283,Gentoo,Biscoe,54.3,15.7,231.0,5650.0,Male
183,Chinstrap,Dream,54.2,20.8,201.0,4300.0,Male
191,Chinstrap,Dream,53.5,19.9,205.0,4500.0,Male
327,Gentoo,Biscoe,53.4,15.8,219.0,5500.0,Male
181,Chinstrap,Dream,52.8,20.0,205.0,4550.0,Male

**26.** How could you sort by species first, then by body mass?

In [123]:
sort2 = df_penguins_full.sort_values(by = ["species", "bill_length_mm"], ascending = False)
sort2.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
253,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,Male
321,Gentoo,Biscoe,55.9,17.0,228.0,5600.0,Male
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,Male
283,Gentoo,Biscoe,54.3,15.7,231.0,5650.0,Male
327,Gentoo,Biscoe,53.4,15.8,219.0,5500.0,Male
301,Gentoo,Biscoe,52.5,15.6,221.0,5450.0,Male
311,Gentoo,Biscoe,52.2,17.1,228.0,5400.0,Male
309,Gentoo,Biscoe,52.1,17.0,230.0,5550.0,Male
333,Gentoo,Biscoe,51.5,16.3,230.0,5500.0,Male
307,Gentoo,Biscoe,51.3,14.2,218.0,5300.0,Male

## Selecting Rows, Columns, and Cells

Let's look at some precious stones now, and leave the poor penguins alone for a while.  Let's look at some precious stones now, and leave the poor penguins alone for a while.

**27.** Load the Seaborn "diamonds" dataset into a Pandas dataframe named diamonds.

In [125]:
df_diamonds = sns.load_dataset("diamonds")
df_diamonds

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

**28.** Display the columns that are available.

In [127]:
df_diamonds.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

**29.** If you select a single column from the diamonds DataFrame, what will be the type of the return value?

pandas series

**30.** Select the 'table' column and show its type

In [129]:
type(df_diamonds["table"])

pandas.core.series.Series

**31.** Select the first ten rows of the price and carat columns ten rows of the diamonds DataFrame into a variable called subset, and display them.

In [134]:
subset = df_diamonds[["price", "carat"]].head(10)
subset

   price  carat
0    326   0.23
1    326   0.21
2    327   0.23
3    334   0.29
4    335   0.31
5    336   0.24
6    336   0.24
7    337   0.26
8    337   0.22
9    338   0.23

**32.** For a given column, show the code to display the datatype of the _values_ in the column?

In [137]:
subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   price   10 non-null     int64
 1   carat   10 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 288.0 bytes

**33.** Select the first row of the diamonds DataFrame into a variable called row.

In [139]:
row = df_diamonds.iloc[0]
row

carat       0.23
cut        Ideal
color          E
clarity      SI2
depth       61.5
table       55.0
price        326
x           3.95
y           3.98
z           2.43
Name: 0, dtype: object

**34.** What would you expect the data type of the row to be?  Display it.

A Pandas series

In [140]:
type(row)

pandas.core.series.Series

**35.** Can you discover the names of the columns using only the row returned in #33?  Why or why not?Can you discover the names of the columns using only the row returned in #33?  Why or why not?

Yes, because a row series should have the columns as the index (See below):

In [145]:
print(row.index)

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

**36.** Select the row with the highest priced diamond.

In [147]:
high = df_diamonds["price"].idxmax()
high

27749

In [149]:
df_diamonds.iloc[high]

carat         2.29
cut        Premium
color            I
clarity        VS2
depth         60.8
table         60.0
price        18823
x              8.5
y             8.47
z             5.16
Name: 27749, dtype: object

In [150]:
df_diamonds["price"].max()

18823

**37.** Select the row with the lowest priced diamond.

In [153]:
low = df_diamonds["price"].idxmin()
low

0

In [154]:
df_diamonds.iloc[low]

carat       0.23
cut        Ideal
color          E
clarity      SI2
depth       61.5
table       55.0
price        326
x           3.95
y           3.98
z           2.43
Name: 0, dtype: object

In [155]:
df_diamonds["price"].min()

326

## Some Exercises Using Time Series

**38.** Load the taxis dataset into a DataFrame, ```taxis```.

In [170]:
df_taxis = sns.load_dataset("taxis")
df_taxis.head(2)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan

**39.** The 'pickup' column contains the date and time the customer picked up, but it's a string.  Add a column to the DataFrame, 'pickup_time', containing the value in 'pickup' as a DateTime.

In [171]:
df_taxis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

In [178]:
df_taxis["pickup_time"] = pd.to_datetime(df_taxis["pickup"])
df_taxis.info()
#df_taxis[pickup].dtype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
 14  pickup_time      6433 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(5), int64(1), object(6)
memory usage: 754.0+ KB

**40.** We have a hypothesis that as the day goes on, the tips get higher.  We'll need to wrangle the data a bit before testing this, however.  First, now that we have a datetime column, pickup_time, create a subset of it to create a new DataFrame, taxis_one_day. This new DataFrame should have values between '2019-03-23 00:06:00' (inclusive) and '2019-03-24 00:00:00' (exlusive).

In [180]:
taxis_one_day = df_taxis[(df_taxis["pickup_time"] >= '2019-03-23 00:06:00') & (df_taxis["pickup_time"] <= "2019-03-24 00:00:00")]
taxis_one_day.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,pickup_time
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan,2019-03-23 20:21:09
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.0,1.00,0.0,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan,2019-03-23 11:48:50
17,2019-03-23 20:50:49,2019-03-23 21:02:07,1,2.60,10.5,2.00,0.0,16.30,yellow,credit card,Midtown Center,East Harlem South,Manhattan,Manhattan,2019-03-23 20:50:49
117,2019-03-23 09:39:25,2019-03-23 09:56:45,0,3.60,15.5,3.75,0.0,22.55,yellow,credit card,Yorkville East,Penn Station/Madison Sq West,Manhattan,Manhattan,2019-03-23 09:39:25
144,2019-03-23 18:35:01,2019-03-23 18:47:39,1,3.20,12.5,2.00,0.0,17.80,yellow,credit card,UN/Turtle Bay South,East Village,Manhattan,Manhattan,2019-03-23 18:35:01

**41.** We now have a range from morning until midnight, but we to take the mean of the numeric columns, grouped at one hour intervals.  Save the result as df_means, and display it.

**42.** Create a simple line plot of the value "distance".

**43.** Overall, do riders travel further or less far as the day progresses?

**44.** Create a new column in taxis_means, ```tip_in_percent```.  The source columns for this should be "fare" and "tip"

**45.** Create a new column, time_interval, as a range of integer values beginning with zero.

Display the correlations between the following pairs of values:
1. tip_in_percent and distance.
1. tip_in_percent and passengers.
1. tip_in_percent and time_interval.

**47.** Admittedly, the size of the data set is fairly small given how we've subsetted it.  But based on the values in #45, which of the three pairs show the strongest correlation.

**48.** Did our hypothesis that people tip more as the day goes on turn out to be warranted?

#**Numpy Questions**


**49.** Write a NumPy program to test whether none of the elements of a given array are zero.

In [183]:
arr1 = np.array([1,5,4,7,2,8,0])
print(np.all(arr1!=0))

False

In [185]:
arr2 = np.array([1,5,4,7,2,8])
print(np.all(arr2!=0))

True


**50.** Write a NumPy program to test if any of the elements of a given array are non-zero.

In [186]:
arr = np.array([0,0,0,0,0])
print(np.all(arr==0))

True

**51.** Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).

np.isnan(x)	Test element-wise for NaN	NaN	inf, -inf, finite numbers        

np.isinf(x)	Test element-wise for infinity	inf, -inf	NaN, finite numbers       

np.isfinite(x)	Test element-wise for finiteness	Finite numbers	NaN, inf, -inf

In [191]:
arr4 = np.array([1,7,4,2,4,17, np.nan])
bool1 = np.isfinite(arr4)
arr4[bool1]

array([ 1.,  7.,  4.,  2.,  4., 17.])

**52.** Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

In [197]:
ones = np.ones(10)
print(ones)
zeros = np.zeros(10)
print(zeros)
fives = np.ones(10)*5
print(fives)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

**53.** Write a NumPy program to create a 3x3 identity matrix.

In [201]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**54.** Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [207]:
x = np.ones((10,10))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**55.** Write a NumPy program to save a given array to a text file and load it.

**56.** Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [208]:
y = np.ones((4,15), dtype = int)
y[1:-1, 1:-1] = 0
y

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

**57.** Write a NumPy program to add a border (filled with 0's) around an existing array.

2. Add a border of zeros using np.pad()

'pad_width=1' adds 1 unit of padding to the beginning and end of each axis

'mode="constant"' specifies a constant value for padding

'constant_values=0' specifies that the constant value is 0

In [213]:
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]

**58.** Write a NumPy program to find common values between two arrays.

In [215]:
arr1 = np.array([0, 10, 20, 40, 60, 10])
arr2 = np.array([10, 30, 40, 10])
np.intersect1d(arr1, arr2)

array([10, 40])

**59.** Write a NumPy program to find the set difference between two arrays. The set difference will return sorted, distinct values in array1 that are not in array2.

In [217]:
np.setdiff1d(arr1, arr2)

array([ 0, 20, 60])

**60.** Write a NumPy program to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order.

In [222]:
arr = np.arange(14)
arr1, arr2, arr3 = np.split(arr, [2,4])
print(arr1, arr2, arr3)

[0 1] [2 3] [ 4  5  6  7  8  9 10 11 12 13]

**61.** Write a NumPy program to create a record array from a (flat) list of arrays.

**Sample arrays:** [1,2,3,4], ['Red', 'Green', 'White', 'Orange'], [12.20,15,20,40]

**Expected Output:**

(1, 'Red', 12.2)
(2, 'Green', 15.0)
(3, 'White', 20.0)

**62.** Write a NumPy program to read a CSV data file and store records in an array.

In [227]:
num = """\
1,10.5,20
2,12.1,22
3,15.0,18
4,9.8,25
"""

In [228]:
with open('num_data.csv', 'w') as f:
    f.write(num)

dn = np.loadtxt('num_data.csv', delimiter=',')
print(dn)

[[ 1.  10.5 20. ]
 [ 2.  12.1 22. ]
 [ 3.  15.  18. ]
 [ 4.   9.8 25. ]]

**63.** Write a NumPy program to count the occurrences of a specified item in a given NumPy array.

In [225]:
arr = np.array([1, 4, 4, 5, 7])
print(np.count_nonzero(arr == 4))

2