In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()

In [ ]:
from google.colab import drive
drive.mount

In [ ]:
filepath="/content/drive/MyDrive/Superstore.csv"
df =  pd.read_csv(filepath,encoding="latin1")

In [ ]:
pd.set_option('display.max_columns', None)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

1. From the Superstore dataset, compute the top 5 states by total profit along with the number of unique customers in each of those states.

In [ ]:
top_5 = df.groupby('State').agg(Total_Profit=('Profit','sum'), Customers=('Customer Name','nunique')).sort_values(by='Total_Profit',ascending=False)
print(top_5.head())

            Total_Profit  Customers
State
California    76381.3871        577
New York      74038.5486        415
Washington    33402.6517        224
Michigan      24463.1876        106
Virginia      18597.9504        107

2. Identify the customer with the highest number of unique orders and display their total sales grouped by category.

In [ ]:
cust = df.groupby('Customer Name')["Order ID"].nunique().sort_values(ascending=False)
cust_max=cust.head(1)
print(cust_max)
df_cust=df[df['Customer Name'].isin(cust_max.index)]
# print(df_cust)  #returns dataframe
df_cust.groupby('Category')['Sales'].sum()

Customer Name
Emily Phan    17
Name: Order ID, dtype: int64

Category
Furniture          2860.0848
Office Supplies    1258.1180
Technology         1359.8580
Name: Sales, dtype: float64

In [ ]:
sale_Sum=df_cust.groupby('Category')['Sales'].sum()
print(sale_Sum)

Category
Furniture          2860.0848
Office Supplies    1258.1180
Technology         1359.8580
Name: Sales, dtype: float64

 3. Create a pivot table of average discount per ship mode, then rank ship modes by total profit. Compare whether higher average discounts align with higher profitability.

In [ ]:
pivot =  df.pivot_table(index='Ship Mode',values='Discount',aggfunc='mean')
print(pivot)

                Discount
Ship Mode
First Class     0.164610
Same Day        0.152394
Second Class    0.138895
Standard Class  0.160023

In [ ]:
df.groupby("Ship Mode")['Discount'].mean()

Ship Mode
First Class       0.164610
Same Day          0.152394
Second Class      0.138895
Standard Class    0.160023
Name: Discount, dtype: float64

4. Divide Sales into quartiles (Q1–Q4) and within each quartile, find the most frequent sub-category by order count. Present the results for all quartiles side by side.

In [ ]:
df['Sales_Q'] = pd.qcut(df['Sales'],4,labels=("Q1","Q2","Q3","Q4"))
df.groupby('Sales_Q')['Sub-Category'].value_counts()

/tmp/ipython-input-345371279.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Sales_Q')['Sub-Category'].value_counts()

Sales_Q  Sub-Category
Q1       Binders         711
         Paper           437
         Art             434
         Furnishings     212
         Labels          202
                        ...
Q4       Supplies         26
         Envelopes        17
         Art              12
         Labels            8
         Fasteners         0
Name: count, Length: 68, dtype: int64

5. Calculate the Interquartile Range (IQR) of Profit and use it to detect outlier profits. List the categories that contain the largest proportion of such outliers.

In [ ]:
q25 =  df['Profit'].quantile(0.25)
q75 =  df['Profit'].quantile(0.75)
iqr =  q75 - q25
print(iqr)
lower_bound = q25 - 1.5*iqr
upper_bound = q75 + 1.5*iqr
df_outlier =  df[(df['Profit'] <= lower_bound) | (df['Profit'] >= upper_bound)]
print(df_outlier)

27.63525
      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
1          2  CA-2013-152156  09-11-2013  12-11-2013    Second Class
3          4  US-2012-108966  11-10-2012  18-10-2012  Standard Class
7          8  CA-2011-115812  09-06-2011  14-06-2011  Standard Class
10        11  CA-2011-115812  09-06-2011  14-06-2011  Standard Class
13        14  CA-2013-161389  06-12-2013  11-12-2013  Standard Class
...      ...             ...         ...         ...             ...
9957    9958  US-2011-143287  11-11-2011  17-11-2011  Standard Class
9962    9963  CA-2012-168088  19-03-2012  22-03-2012     First Class
9968    9969  CA-2014-153871  12-12-2014  18-12-2014  Standard Class
9979    9980  US-2013-103674  07-12-2013  11-12-2013  Standard Class
9993    9994  CA-2014-119914  05-05-2014  10-05-2014    Second Class

     Customer ID     Customer Name      Segment        Country  \
1       CG-12520       Claire Gute     Consumer  United States
3       SO-20335    Sean O'Donnell     Consumer  United States
7       BH-11710   Brosina Hoffman     Consumer  United States
10      BH-11710   Brosina Hoffman     Consumer  United States
13      IM-15070      Irene Maddox     Consumer  United States
...          ...               ...          ...            ...
9957    KN-16705     Kristina Nunn  Home Office  United States
9962    CM-12655  Corinna Mitchell  Home Office  United States
9968    RB-19435   Richard Bierner     Consumer  United States
9979    AP-10720        Anne Pryor  Home Office  United States
9993    CC-12220      Chris Cortes     Consumer  United States

                 City       State  Postal Code   Region       Product ID  \
1           Henderson    Kentucky        42420    South  FUR-CH-10000454
3     Fort Lauderdale     Florida        33311    South  FUR-TA-10000577
7         Los Angeles  California        90032     West  TEC-PH-10002275
10        Los Angeles  California        90032     West  FUR-TA-10001539
13            Seattle  Washington        98103     West  OFF-BI-10003656
...               ...         ...          ...      ...              ...
9957     New Rochelle    New York        10801     East  OFF-PA-10004039
9962          Houston       Texas        77041  Central  FUR-BO-10004218
9968       Plainfield  New Jersey         7060     East  OFF-BI-10004600
9979      Los Angeles  California        90032     West  OFF-BI-10002026
9993      Westminster  California        92683     West  OFF-AP-10002684

             Category Sub-Category  \
1           Furniture       Chairs
3           Furniture       Tables
7          Technology       Phones
10          Furniture       Tables
13    Office Supplies      Binders
...               ...          ...
9957  Office Supplies        Paper
9962        Furniture    Bookcases
9968  Office Supplies      Binders
9979  Office Supplies      Binders
9993  Office Supplies   Appliances

                                           Product Name      Sales  Quantity  \
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.9400         3
3         Bretford CR4500 Series Slim Rectangular Table   957.5775         5
7                        Mitel 5320 IP Phone VoIP phone   907.1520         6
10             Chromcraft Rectangular Conference Tables  1706.1840         9
13          Fellowes PB200 Plastic Comb Binding Machine   407.9760         3
...                                                 ...        ...       ...
9957                                         Xerox 1882   223.9200         4
9962  Bush Heritage Pine Collection 5-Shelf Bookcase...   383.4656         4
9968          Ibico Ibimaster 300 Manual Binding System   735.9800         2
9979                  Ibico Recycled Linen-Style Covers   437.4720        14
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...   243.1600         2

      Discount    Profit Sales_Q
1         0.00  219.5820      Q4
3         0.45 -383.0310      Q4
7         0.20   90.7152      Q4
10        0.20   85.3092      Q4
13        0.20  132.5922      Q4
...        ...       ...     ...
9957      0.00  109.7208      Q4
9962      0.32  -67.6704      Q4
9968      0.00  331.1910      Q4
9979      0.20  153.1152      Q4
9993      0.00   72.9480      Q4

[1881 rows x 22 columns]

In [ ]:
# value_counts()
category = df_outlier.groupby('Category').size()
print(category)

Category
Furniture          627
Office Supplies    685
Technology         569
dtype: int64

6. Filter the dataset for California and Texas. Compare the mean profit per order for both states, and identify which state shows higher standard deviation of profit.

In [ ]:
df_cali=df[df['State'].isin(['California','Texas'])]
print(df_cali)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
2          3  CA-2013-138688  13-06-2013  17-06-2013    Second Class
5          6  CA-2011-115812  09-06-2011  14-06-2011  Standard Class
6          7  CA-2011-115812  09-06-2011  14-06-2011  Standard Class
7          8  CA-2011-115812  09-06-2011  14-06-2011  Standard Class
8          9  CA-2011-115812  09-06-2011  14-06-2011  Standard Class
...      ...             ...         ...         ...             ...
9986    9987  CA-2013-125794  30-09-2013  04-10-2013  Standard Class
9990    9991  CA-2014-121258  27-02-2014  04-03-2014  Standard Class
9991    9992  CA-2014-121258  27-02-2014  04-03-2014  Standard Class
9992    9993  CA-2014-121258  27-02-2014  04-03-2014  Standard Class
9993    9994  CA-2014-119914  05-05-2014  10-05-2014    Second Class

     Customer ID    Customer Name    Segment        Country         City  \
2       DV-13045  Darrin Van Huff  Corporate  United States  Los Angeles
5       BH-11710  Brosina Hoffman   Consumer  United States  Los Angeles
6       BH-11710  Brosina Hoffman   Consumer  United States  Los Angeles
7       BH-11710  Brosina Hoffman   Consumer  United States  Los Angeles
8       BH-11710  Brosina Hoffman   Consumer  United States  Los Angeles
...          ...              ...        ...            ...          ...
9986    ML-17410     Maris LaWare   Consumer  United States  Los Angeles
9990    DB-13060      Dave Brooks   Consumer  United States   Costa Mesa
9991    DB-13060      Dave Brooks   Consumer  United States   Costa Mesa
9992    DB-13060      Dave Brooks   Consumer  United States   Costa Mesa
9993    CC-12220     Chris Cortes   Consumer  United States  Westminster

           State  Postal Code Region       Product ID         Category  \
2     California        90036   West  OFF-LA-10000240  Office Supplies
5     California        90032   West  FUR-FU-10001487        Furniture
6     California        90032   West  OFF-AR-10002833  Office Supplies
7     California        90032   West  TEC-PH-10002275       Technology
8     California        90032   West  OFF-BI-10003910  Office Supplies
...          ...          ...    ...              ...              ...
9986  California        90008   West  TEC-AC-10003399       Technology
9990  California        92627   West  FUR-FU-10000747        Furniture
9991  California        92627   West  TEC-PH-10003645       Technology
9992  California        92627   West  OFF-PA-10004041  Office Supplies
9993  California        92683   West  OFF-AP-10002684  Office Supplies

     Sub-Category                                       Product Name    Sales  \
2          Labels  Self-Adhesive Address Labels for Typewriters b...   14.620
5     Furnishings  Eldon Expressions Wood and Plastic Desk Access...   48.860
6             Art                                         Newell 322    7.280
7          Phones                     Mitel 5320 IP Phone VoIP phone  907.152
8         Binders  DXL Angle-View Binders with Locking Rings by S...   18.504
...           ...                                                ...      ...
9986  Accessories  Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...   36.240
9990  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960
9991       Phones                              Aastra 57i VoIP phone  258.576
9992        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600
9993   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160

      Quantity  Discount   Profit Sales_Q
2            2       0.0   6.8714      Q1
5            7       0.0  14.1694      Q2
6            4       0.0   1.9656      Q1
7            6       0.2  90.7152      Q4
8            3       0.2   5.7825      Q2
...        ...       ...      ...     ...
9986         1       0.0  15.2208      Q2
9990         2       0.0  15.6332      Q3
9991         2       0.2  19.3932      Q4
9992         4       0.0  13.3200      Q2
9993         2       0.0  72.9480      Q4

[2986 rows x 22 columns]

In [ ]:
mean = df_cali.groupby('State')['Profit'].mean().sort_values(ascending=False)
std = df_cali.groupby('State')['Profit'].std().sort_values(ascending=False)
print(mean)
print(std.head(2))

State
California    38.171608
Texas        -26.121174
Name: Profit, dtype: float64
State
Texas         189.022781
California     97.691593
Name: Profit, dtype: float64

7. Add a new column labeling each row as Profit or Loss. For each region, compute the ratio of profitable to loss-making orders and determine the region with the healthiest ratio.

In [ ]:
# df["Profit_Loss"] = pd.apply(lambda x: "Positive" if df['Profit'] > 0 else "Negative")

df['Profit_Loss'] = df['Profit'].apply(lambda x: 'Profit' if x > 0 else 'Loss')
print(df)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2013-152156  09-11-2013  12-11-2013    Second Class
1          2  CA-2013-152156  09-11-2013  12-11-2013    Second Class
2          3  CA-2013-138688  13-06-2013  17-06-2013    Second Class
3          4  US-2012-108966  11-10-2012  18-10-2012  Standard Class
4          5  US-2012-108966  11-10-2012  18-10-2012  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2011-110422  22-01-2011  24-01-2011    Second Class
9990    9991  CA-2014-121258  27-02-2014  04-03-2014  Standard Class
9991    9992  CA-2014-121258  27-02-2014  04-03-2014  Standard Class
9992    9993  CA-2014-121258  27-02-2014  04-03-2014  Standard Class
9993    9994  CA-2014-119914  05-05-2014  10-05-2014    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

           State  Postal Code Region       Product ID         Category  \
0       Kentucky        42420  South  FUR-BO-10001798        Furniture
1       Kentucky        42420  South  FUR-CH-10000454        Furniture
2     California        90036   West  OFF-LA-10000240  Office Supplies
3        Florida        33311  South  FUR-TA-10000577        Furniture
4        Florida        33311  South  OFF-ST-10000760  Office Supplies
...          ...          ...    ...              ...              ...
9989     Florida        33180  South  FUR-FU-10001889        Furniture
9990  California        92627   West  FUR-FU-10000747        Furniture
9991  California        92627   West  TEC-PH-10003645       Technology
9992  California        92627   West  OFF-PA-10004041  Office Supplies
9993  California        92683   West  OFF-AP-10002684  Office Supplies

     Sub-Category                                       Product Name  \
0       Bookcases                  Bush Somerset Collection Bookcase
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
2          Labels  Self-Adhesive Address Labels for Typewriters b...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
4         Storage                     Eldon Fold 'N Roll Cart System
...           ...                                                ...
9989  Furnishings                             Ultra Door Pull Handle
9990  Furnishings  Tenex B1-RE Series Chair Mats for Low Pile Car...
9991       Phones                              Aastra 57i VoIP phone
9992        Paper  It's Hot Message Books with Stickers, 2 3/4" x 5"
9993   Appliances  Acco 7-Outlet Masterpiece Power Center, Wihtou...

         Sales  Quantity  Discount    Profit Profit_Loss
0     261.9600         2      0.00   41.9136      Profit
1     731.9400         3      0.00  219.5820      Profit
2      14.6200         2      0.00    6.8714      Profit
3     957.5775         5      0.45 -383.0310        Loss
4      22.3680         2      0.20    2.5164      Profit
...        ...       ...       ...       ...         ...
9989   25.2480         3      0.20    4.1028      Profit
9990   91.9600         2      0.00   15.6332      Profit
9991  258.5760         2      0.20   19.3932      Profit
9992   29.6000         4      0.00   13.3200      Profit
9993  243.1600         2      0.00   72.9480      Profit

[9994 rows x 22 columns]

8. Generate the list of top 10 most profitable products. Then, compare it with the sub-categories that have the lowest average profit. Report whether any product from these low-profit sub-categories still appears in the overall top 10 list.

In [ ]:
list_profit = df.groupby('Product Name')['Profit'].sum().sort_values(ascending=False).head(10)
print(list_profit)

sub_cat = df.groupby('Sub-Category')['Profit'].mean().sort_values(ascending=True).head(10)
print(sub_cat)

#Comparision
print(list_profit.index.isin(sub_cat.index))

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Ativa V4110MDD Micro-Cut Shredder                                               3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta                                3717.9714
Plantronics Savi W720 Multi-Device Wireless Headset System                      3696.2820
Ibico EPK-21 Electric Binding System                                            3345.2823
Zebra ZM400 Thermal Label Printer                                               3343.5360
Name: Profit, dtype: float64
Sub-Category
Tables        -55.565771
Bookcases     -15.230509
Supplies       -6.258418
Fasteners       4.375660
Art             8.200737
Furnishings    13.645918
Labels         15.236962
Binders        19.843574
Paper          24.856620
Storage        25.152277
Name: Profit, dtype: float64
[False False False False False False False False False False]